import type { MovieFormat, MovieLanguageType, MoviePresentationRequest, MovieProjectionType } from "@/api/movieApi";
import type { TicketPriceConfig } from "@/api/ticketPricingApi";

export type PresentationLike = {
  presentationName?: string | null;
  displayName?: string | null;
  label?: string | null;
  presentationFormat?: string | null;
  format?: MovieFormat | string | null;
  projectionType?: MovieProjectionType | string | null;
  languageType?: MovieLanguageType | string | null;
  active?: boolean | null;
};

const FORMAT_LABELS: Record<string, string> = {
  STANDARD: "Standard",
  STANDARD_2D: "Standard",
  STANDARD_3D: "Standard",
  IMAX: "IMAX",
  _4DX: "4DX",
  "4DX": "4DX",
};

export function normalizeMovieFormat(value?: string | null) {
  const normalized = String(value || "").trim().toUpperCase();
  if (!normalized) return "";
  if (normalized === "2D" || normalized === "3D" || normalized === "STANDARD") return "STANDARD";
  if (normalized === "4DX") return "_4DX";
  if (normalized === "DOLBY") return "STANDARD";
  return normalized;
}

export function formatMovieFormat(value?: string | null) {
  const normalized = normalizeMovieFormat(value);
  return FORMAT_LABELS[normalized] || value || "";
}

export function formatProjectionLabel(value?: string | null) {
  const normalized = String(value || "").trim().toUpperCase();
  if (normalized === "TWO_D" || normalized === "2D") return "2D";
  if (normalized === "THREE_D" || normalized === "3D") return "3D";
  return value || "";
}

export function isProjectionAllowedForFormat(
  format?: string | null,
  projectionType?: string | null,
): boolean {
  const normalizedFormat = normalizeMovieFormat(format);
  const projection = formatProjectionLabel(projectionType);
  return normalizedFormat === "STANDARD"
    ? projection === "2D" || projection === "3D"
    : projection === "3D";
}

export function formatLanguageLabel(value?: string | null) {
  const normalized = String(value || "").trim().toUpperCase();
  if (normalized === "SUBTITLE" || normalized === "PHU_DE" || normalized === "PHỤ ĐỀ") return "Phụ đề";
  if (normalized === "DUBBED" || normalized === "LONG_TIENG" || normalized === "LỒNG TIẾNG") return "Lồng tiếng";
  if (normalized === "ORIGINAL" || normalized === "NGUYEN_BAN" || normalized === "NGUYÊN BẢN") return "Nguyên bản";
  return value || "";
}

export function isAutoGeneratedPresentationLabel(value?: string | null): boolean {
  const normalized = String(value || "").trim().toUpperCase();
  if (!normalized) return false;
  const startsWithFormat = ["STANDARD -", "IMAX -", "4DX -", "DOLBY -"]
    .some((prefix) => normalized.startsWith(prefix));
  return startsWithFormat && (normalized.includes("2D") || normalized.includes("3D"));
}

export function formatPresentationLabelFromFields(presentation?: PresentationLike | null): string {
  if (!presentation) return "";
  const projectionLabel = formatProjectionLabel(presentation.projectionType);
  // Tên tùy chỉnh vẫn phải thể hiện 2D/3D để hai phiên bản không bị nhìn thành một.
  const configuredName = presentation.displayName || presentation.presentationName || presentation.label;
  if (configuredName
      && configuredName !== "Phiên bản chiếu"
      && !isAutoGeneratedPresentationLabel(configuredName)) {
    const normalizedName = configuredName.toUpperCase();
    return projectionLabel && !normalizedName.includes(projectionLabel.toUpperCase())
      ? `${configuredName} · ${projectionLabel}`
      : configuredName;
  }
  
  const formatStr = presentation.presentationFormat || presentation.format;
  const parts = [
    formatMovieFormat(formatStr),
    projectionLabel,
    formatLanguageLabel(presentation.languageType)
  ].filter(Boolean);

  if (parts.length === 0) {
    return "Phiên bản chiếu";
  }
  return parts.join(" · ");
}

export function getSuggestedPresentationBasePrice(
  defaultPrice: number,
  presentation?: PresentationLike | null,
  config?: TicketPriceConfig | null,
): number {
  if (!presentation) return config?.standard2dPrice ?? defaultPrice;
  const format = normalizeMovieFormat(String(presentation.format ?? presentation.presentationFormat ?? "STANDARD"));
  const projection = formatProjectionLabel(presentation.projectionType);
  if (config) {
    if (format === "IMAX") return config.imax3dPrice;
    if (format === "_4DX" || format === "4DX") return config.fourDx3dPrice;
    if (projection === "3D") return config.standard3dPrice;
    return config.standard2dPrice;
  }
  const formatSurcharge = format === "IMAX" ? 30_000 : (format === "_4DX" || format === "4DX") ? 40_000 : 0;
  const projectionSurcharge = projection === "3D" ? 20_000 : 0;
  return defaultPrice + formatSurcharge + projectionSurcharge;
}

export function getActivePresentationLabels(presentations?: MoviePresentationRequest[] | null) {
  return (presentations || [])
    .filter((presentation) => presentation.active !== false)
    .sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0))
    .map(formatPresentationLabelFromFields)
    .filter(Boolean);
}
