import { useCallback, useEffect, useState } from "react";
import { FileSearch, Loader2, RefreshCw, Search } from "lucide-react";
import { toast } from "react-toastify";
import { staffAuditLogApi, type StaffAuditLogResponse } from "@/api/staffAuditLogApi";

const actionLabels: Record<string, string> = { CREATE: "Tạo mới", UPDATE: "Cập nhật", STATUS_CHANGE: "Đổi trạng thái", DEACTIVATE: "Vô hiệu hóa", CANCEL: "Hủy ca", CHECK_IN: "Vào ca", CHECK_OUT: "Ra ca" };
const typeLabels: Record<string, string> = { STAFF_ACCOUNT: "Tài khoản", STAFF_SCHEDULE: "Lịch ca", STAFF_ATTENDANCE: "Chấm công" };

export function StaffAuditLogPage() {
  const [logs, setLogs] = useState<StaffAuditLogResponse[]>([]);
  const [keyword, setKeyword] = useState("");
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setLogs(await staffAuditLogApi.list(keyword.trim() || undefined)); } catch { toast.error("Không thể tải nhật ký nhân viên"); } finally { setLoading(false); } }, [keyword]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  return <div className="flex-1 overflow-auto bg-slate-50 p-6" style={{ fontFamily: "Inter, sans-serif" }}><div className="mx-auto max-w-[1450px]"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-slate-900">Nhật ký hoạt động nhân viên</h1><p className="mt-1 text-sm text-slate-500">Theo dõi thay đổi tài khoản, lịch ca và chấm công để đối soát trách nhiệm.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-semibold text-slate-600"><RefreshCw size={16} /> Làm mới</button></div><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2 rounded-xl border px-3 py-2 md:max-w-md"><Search size={17} className="text-slate-400" /><input value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Tìm nhân viên, người thao tác..." className="w-full text-sm outline-none" /></div>{loading ? <div className="flex h-32 items-center justify-center text-slate-400"><Loader2 className="mr-2 animate-spin" size={18} /> Đang tải...</div> : <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b text-xs uppercase tracking-wide text-slate-400"><th className="pb-3">Thời điểm</th><th className="pb-3">Đối tượng</th><th className="pb-3">Thao tác</th><th className="pb-3">Người thực hiện</th><th className="pb-3">Chi tiết</th></tr></thead><tbody>{logs.map((log) => <tr key={log.auditLogId} className="border-b last:border-0"><td className="py-3 text-slate-500">{log.createdAt ? new Date(log.createdAt).toLocaleString("vi-VN") : "—"}</td><td className="py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{typeLabels[log.targetType] || log.targetType}</span><div className="mt-1 font-semibold text-slate-800">{log.targetName || "—"}</div></td><td className="py-3 font-semibold text-amber-700">{actionLabels[log.action] || log.action}</td><td className="py-3 text-slate-600">{log.actorUsername || "system"}</td><td className="py-3 text-slate-500">{log.summary || log.reason || "—"}</td></tr>)}</tbody></table>{!logs.length && <div className="py-12 text-center text-sm text-slate-400"><FileSearch className="mx-auto mb-2" size={24} />Chưa có hoạt động được ghi nhận</div>}</div>}</section></div></div>;
}
