package org.example.hcm26_cpl_js_java_02_team4_movie_theater.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.FieldDefaults;
import org.example.hcm26_cpl_js_java_02_team4_movie_theater.entity.enums.MovieFormat;
import org.example.hcm26_cpl_js_java_02_team4_movie_theater.entity.enums.MovieLanguageType;
import org.example.hcm26_cpl_js_java_02_team4_movie_theater.entity.enums.MovieProjectionType;

@Entity
@Table(name = "movie_presentation")
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
public class MoviePresentation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "presentation_id")
    Long presentationId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "movie_id", nullable = false)
    Movie movie;

    @Enumerated(EnumType.STRING)
    @Column(name = "format", nullable = false, length = 20)
    MovieFormat format;

    @Enumerated(EnumType.STRING)
    @Column(name = "projection_type", nullable = false, length = 20)
    MovieProjectionType projectionType;

    @Enumerated(EnumType.STRING)
    @Column(name = "language_type", nullable = false, length = 20)
    MovieLanguageType languageType;

    @Column(name = "audio_language", length = 80)
    String audioLanguage;

    @Column(name = "subtitle_language", length = 80)
    String subtitleLanguage;

    @Column(name = "label", length = 120)
    String label;

    @Builder.Default
    @Column(name = "active", nullable = false)
    Boolean active = true;

    @Builder.Default
    @Column(name = "sort_order")
    Integer sortOrder = 0;

    @Transient
    public String getDisplayName() {
        if (label != null && !label.isBlank() && !isAutoGeneratedLabel(label)) {
            String configuredLabel = label.trim();
            String projection = projectionType == null ? "" : projectionType.toDisplayString();
            return !projection.isBlank() && !configuredLabel.toUpperCase().contains(projection.toUpperCase())
                    ? configuredLabel + " · " + projection
                    : configuredLabel;
        }
        StringBuilder builder = new StringBuilder();
        appendPart(builder, format == null ? null : format.toDisplayString());
        appendPart(builder, projectionType == null ? null : projectionType.toDisplayString());
        appendPart(builder, languageType == null ? null : languageType.toDisplayString());
        return builder.isEmpty() ? "Phiên bản chiếu" : builder.toString();
    }

    private boolean isAutoGeneratedLabel(String value) {
        String normalized = value.trim().toUpperCase();
        boolean startsWithFormat = normalized.startsWith("STANDARD -")
                || normalized.startsWith("IMAX -")
                || normalized.startsWith("4DX -")
                || normalized.startsWith("DOLBY -");
        return startsWithFormat && (normalized.contains("2D") || normalized.contains("3D"));
    }

    private void appendPart(StringBuilder builder, String value) {
        if (value == null || value.isBlank()) {
            return;
        }
        if (!builder.isEmpty()) {
            builder.append(" · ");
        }
        builder.append(value.trim());
    }
}
